### ISSUE TITLE
Terminal list tab location

### ISSUE THREAD

**Issue by htjain** [YashTotale/terminal-all-in-one#148]
![image](https://user-images.githubusercontent.com/46592577/115380450-3480a080-a1f0-11eb-9a4d-cc1d9d33732b.png)

Currently terminal list tab shows in the left side of the terminals. Is it possible to move it to top or VScode status bar?

**Comment by YashTotale** [comment]
Hey @htjain,

Thanks for reaching out about this request! I think that the terminal list tab is a VS Code feature that is in-built, not a feature that is provided by this extension. The best place to open this issue is probably in the [VS Code repository](https://github.com/microsoft/vscode).

**Comment by htjain** [comment]
Sorry my bad I thought "terminal-all-in-one" added those tabs :) looks like its new feature in VSCode.
