### ISSUE TITLE
How to call runscript with script name or index

### ISSUE THREAD

**Issue by super-tomcat** [YashTotale/terminal-all-in-one#239]
Hi, is it possible to call the command: terminalAllInOne.runScript, with the name or index of a script that will automatically run?

For example if my first script was called 'Open New Terminal' how can i run it directly without having to select it in a picker?

Can i call it by its name or an index?

Thanks

**Comment by YashTotale** [comment]
Hi @super-tomcat,

Thanks for the question! Currently, you can run an individual script by pressing `cmd/ctrl + i` and then the index of the script.

For example, if my scripts were:

```json
{
  "terminalAllInOne.scripts": [
    {
      "name": "Greet",
      "script": ["echo hello", "echo How was your day?"]
    }
  ]
}
```
I could run the "Greet" script by running `cmd/ctrl + i` and then pressing 0. (Note: only indexes 0-9 are possible through this keybinding)

Hope this helps!
